context.objects = [
    {
        factory = adapter
        args = {
            factory.name = support.null-audio-sink
            node.name = "Discord Inject"
            media.class = Audio/Sink
            audio.position = [ FL FR ]
            monitor.channel-volumes = true
            monitor.passthrough = true
        }
    }
    {
        factory = adapter
        args = {
            factory.name = support.null-audio-sink
            node.name = "Output"
            media.class = Audio/Sink
            audio.position = [ FL FR ]
            monitor.channel-volumes = true
            monitor.passthrough = true
        }
    }
]
